spring:
  application:
    name: SW_AI_Doc

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-1.5-pro

logging:
  level:
    root: INFO
    com.sw.sw_ai_doc.domain.ai: DEBUG
